//! Xenith's bootloader-to-kernel wire protocol.

/// Identifies a [`XenithBootInfo`] handoff and catches wrong calling conventions early.
pub const XENITH_BOOT_MAGIC: u64 = 0x5845_4E49_5448_4249;
/// Current backward-compatible protocol version.
pub const XENITH_BOOT_VERSION: u32 = 1;

/// Physical memory ownership recorded by the bootloader.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(u32)]
pub enum BootMemoryKind {
    Usable = 0,
    Reserved = 1,
    AcpiReclaimable = 2,
    AcpiNvs = 3,
    BootloaderReclaimable = 4,
    KernelAndModules = 5,
    Framebuffer = 6,
    BadMemory = 7,
}

/// One physical-memory interval. All fields use little-endian native integers.
#[derive(Clone, Copy, Debug)]
#[repr(C)]
pub struct XenithMemoryRegion {
    pub base: u64,
    pub length: u64,
    pub kind: BootMemoryKind,
    pub reserved: u32,
}

/// Linear framebuffer selected by firmware or the BIOS loader.
#[derive(Clone, Copy, Debug, Default)]
#[repr(C)]
pub struct XenithFramebuffer {
    pub address: u64,
    pub pitch: u32,
    pub width: u32,
    pub height: u32,
    pub bpp: u16,
    pub red_shift: u8,
    pub red_size: u8,
    pub green_shift: u8,
    pub green_size: u8,
    pub blue_shift: u8,
    pub blue_size: u8,
}

/// A loader-owned byte blob, normally the initramfs.
#[derive(Clone, Copy, Debug)]
#[repr(C)]
pub struct XenithModule {
    pub address: u64,
    pub length: u64,
    pub path: *const u8,
    pub path_length: u32,
    pub reserved: u32,
}

/// Complete handoff generated by Xenith BIOS and UEFI loaders.
///
/// Pointers are physical unless their field explicitly says otherwise. The kernel reaches
/// them through `hhdm_offset` before reclaiming loader memory.
#[derive(Clone, Copy, Debug)]
#[repr(C)]
pub struct XenithBootInfo {
    pub magic: u64,
    pub version: u32,
    pub size: u32,
    pub hhdm_offset: u64,
    pub memory_map: *const XenithMemoryRegion,
    pub memory_map_count: u32,
    pub memory_map_entry_size: u32,
    pub framebuffer: XenithFramebuffer,
    pub rsdp: u64,
    pub modules: *const XenithModule,
    pub module_count: u32,
    pub reserved: u32,
    pub command_line: *const u8,
    pub command_line_length: u32,
    pub boot_cpu_apic_id: u32,
}

impl XenithBootInfo {
    /// Build a header with no optional data. Loaders fill the remaining descriptors in place.
    #[must_use]
    pub const fn empty() -> Self {
        Self {
            magic: XENITH_BOOT_MAGIC,
            version: XENITH_BOOT_VERSION,
            size: core::mem::size_of::<Self>() as u32,
            hhdm_offset: 0,
            memory_map: core::ptr::null(),
            memory_map_count: 0,
            memory_map_entry_size: core::mem::size_of::<XenithMemoryRegion>() as u32,
            framebuffer: XenithFramebuffer {
                address: 0,
                pitch: 0,
                width: 0,
                height: 0,
                bpp: 0,
                red_shift: 0,
                red_size: 0,
                green_shift: 0,
                green_size: 0,
                blue_shift: 0,
                blue_size: 0,
            },
            rsdp: 0,
            modules: core::ptr::null(),
            module_count: 0,
            reserved: 0,
            command_line: core::ptr::null(),
            command_line_length: 0,
            boot_cpu_apic_id: 0,
        }
    }

    #[must_use]
    pub const fn is_compatible(&self) -> bool {
        self.magic == XENITH_BOOT_MAGIC
            && self.version == XENITH_BOOT_VERSION
            && self.size as usize >= core::mem::size_of::<Self>()
            && self.memory_map_entry_size as usize == core::mem::size_of::<XenithMemoryRegion>()
    }
}

// The protocol is copied between cores and only contains immutable descriptors after handoff.
unsafe impl Send for XenithBootInfo {}
unsafe impl Sync for XenithBootInfo {}
