//! Stable data structures shared by the Xenith kernel, bootloader, and userspace.

#![no_std]

pub mod boot;
pub mod syscall;

pub use boot::{
    BootMemoryKind, XenithBootInfo, XenithFramebuffer, XenithMemoryRegion, XenithModule,
    XENITH_BOOT_MAGIC, XENITH_BOOT_VERSION,
};
pub use syscall::{
    DirectoryEntry, Errno, NetInterfaceInfo, OpenFlags, SigAction, SigAltStack, SigInfo, SigSet,
    SignalFrame, SockAddrV4, Stat, SyscallNumber, TerminalAttributes, Timespec, UiDisplayInfo,
    UiInputEvent, UiRect, UtsName, WindowSize, AF_INET, ECHO, ECHOE, ECHOK, ECHONL, FIONREAD,
    GRND_NONBLOCK, ICANON, ICRNL, IPPROTO_ICMP, IPPROTO_TCP, IPPROTO_UDP, ISIG, MAP_ANONYMOUS,
    MAP_FIXED, MAP_PRIVATE, MAP_SHARED, MAXSIGSTKSZ, MAX_SOCKET_IO, MINSIGSTKSZ, NET_IF_CONFIGURED,
    NET_IF_DHCP, NET_IF_LINK_UP, NSIG, ONLCR, OPOST, PROT_EXEC, PROT_NONE, PROT_READ, PROT_WRITE,
    SA_NODEFER, SA_ONSTACK, SA_RESETHAND, SA_RESTART, SA_SIGINFO, SA_SUPPORTED, SIGABRT, SIGALRM,
    SIGBUS, SIGCHLD, SIGCONT, SIGFPE, SIGHUP, SIGILL, SIGINT, SIGKILL, SIGNAL_FRAME_ALTSTACK,
    SIGNAL_FRAME_RESTART, SIGNAL_FRAME_XSTATE, SIGNAL_XSTATE_MAX, SIGPIPE, SIGQUIT, SIGSEGV,
    SIGSTOP, SIGTERM, SIGTRAP, SIGTSTP, SIGTTIN, SIGTTOU, SIGUSR1, SIGUSR2, SIG_BLOCK, SIG_DFL,
    SIG_IGN, SIG_SETMASK, SIG_UNBLOCK, SI_KERNEL, SI_USER, SOCK_DGRAM, SOCK_RAW, SOCK_STREAM,
    SPAWN_GROUP_INHERIT, SPAWN_GROUP_NEW, SS_DISABLE, SS_ONSTACK, TCGETS, TCSETS, TCSETSF, TCSETSW,
    TIOCGPGRP, TIOCGPTN, TIOCGWINSZ, TIOCSPGRP, TIOCSWINSZ, UI_ABI_VERSION,
    UI_DISPLAY_NATIVE_PIXEL_FORMAT, UI_EVENT_FLAG_OVERFLOW, UI_EVENT_FLAG_PRESSED,
    UI_EVENT_FLAG_REPEAT, UI_EVENT_KEY, UI_EVENT_POINTER, UI_MAX_DAMAGE_RECTS,
    UI_MAX_EVENTS_PER_READ, UI_MODIFIER_CAPS_LOCK, UI_MODIFIER_LEFT_ALT, UI_MODIFIER_LEFT_CTRL,
    UI_MODIFIER_LEFT_SHIFT, UI_MODIFIER_LEFT_SUPER, UI_MODIFIER_NUM_LOCK, UI_MODIFIER_RIGHT_ALT,
    UI_MODIFIER_RIGHT_CTRL, UI_MODIFIER_RIGHT_SHIFT, UI_MODIFIER_RIGHT_SUPER,
    UI_MODIFIER_SCROLL_LOCK, UI_POINTER_BUTTON_BACK, UI_POINTER_BUTTON_FORWARD,
    UI_POINTER_BUTTON_LEFT, UI_POINTER_BUTTON_MIDDLE, UI_POINTER_BUTTON_RIGHT, UI_TIMEOUT_INFINITE,
    VEOF, VEOL, VERASE, VINTR, VKILL, VMIN, VQUIT, VSUSP, VTIME, WCONTINUED, WNOHANG, WUNTRACED,
};
