//! Stable data structures shared by the Xenith kernel, bootloader, and userspace.

#![no_std]

pub mod boot;
pub mod compositor;
pub mod ipc;
pub mod spawn;
pub mod syscall;
pub mod thread;
pub mod wait;
pub mod windows;

pub use boot::{
    BootMemoryKind, XenithBootInfo, XenithFramebuffer, XenithMemoryRegion, XenithModule,
    XENITH_BOOT_MAGIC, XENITH_BOOT_VERSION,
};
pub use ipc::{
    IpcChannelPair, IpcReceiveMessage, IpcReceiveTransfer, IpcSendMessage, IpcSendTransfer,
    IPC_ABI_VERSION, IPC_CHANNEL_PAIR_SIZE, IPC_MAX_MESSAGE_BYTES, IPC_MAX_TRANSFERS,
    IPC_MESSAGE_HEADER_SIZE, IPC_MESSAGE_RECORD_SIZE, IPC_TIMEOUT_INFINITE,
    IPC_TRANSFER_RIGHTS_ALL, IPC_TRANSFER_RIGHT_MAP, IPC_TRANSFER_RIGHT_READ,
    IPC_TRANSFER_RIGHT_TRANSFER, IPC_TRANSFER_RIGHT_WRITE, IPC_TRANSFER_SIZE,
};
pub use spawn::{
    SpawnFileAction, SpawnRestrictedRequest, SPAWN_FILE_ACTION_SIZE, SPAWN_RESTRICTED_ABI_VERSION,
    SPAWN_RESTRICTED_HEADER_SIZE, SPAWN_RESTRICTED_MAX_FILE_ACTIONS, SPAWN_RESTRICTED_REQUEST_SIZE,
};
pub use syscall::{
    DirectoryEntry, Errno, NetInterfaceInfo, OpenFlags, SigAction, SigAltStack, SigInfo, SigSet,
    SignalFrame, SockAddrV4, Stat, SyscallNumber, TerminalAttributes, Timespec, UiDisplayInfo,
    UiInputEvent, UiRect, UtsName, WindowSize, AF_INET, DIRECTORY_ENTRY_KIND_BLOCK_DEVICE,
    DIRECTORY_ENTRY_KIND_CHARACTER_DEVICE, DIRECTORY_ENTRY_KIND_DIRECTORY,
    DIRECTORY_ENTRY_KIND_REGULAR, DIRECTORY_ENTRY_KIND_SYMLINK, DIRECTORY_ENTRY_KIND_UNKNOWN, ECHO,
    ECHOE, ECHOK, ECHONL, FIONREAD, GRND_NONBLOCK, ICANON, ICRNL, IPPROTO_ICMP, IPPROTO_TCP,
    IPPROTO_UDP, ISIG, MAP_ANONYMOUS, MAP_FIXED, MAP_PRIVATE, MAP_SHARED, MAXSIGSTKSZ,
    MAX_SOCKET_IO, MINSIGSTKSZ, NET_IF_CONFIGURED, NET_IF_DHCP, NET_IF_LINK_UP, NSIG, ONLCR, OPOST,
    PROT_EXEC, PROT_NONE, PROT_READ, PROT_WRITE, SA_NODEFER, SA_ONSTACK, SA_RESETHAND, SA_RESTART,
    SA_SIGINFO, SA_SUPPORTED, SIGABRT, SIGALRM, SIGBUS, SIGCHLD, SIGCONT, SIGFPE, SIGHUP, SIGILL,
    SIGINT, SIGKILL, SIGNAL_FRAME_ALTSTACK, SIGNAL_FRAME_RESTART, SIGNAL_FRAME_XSTATE,
    SIGNAL_XSTATE_MAX, SIGPIPE, SIGQUIT, SIGSEGV, SIGSTOP, SIGTERM, SIGTRAP, SIGTSTP, SIGTTIN,
    SIGTTOU, SIGUSR1, SIGUSR2, SIG_BLOCK, SIG_DFL, SIG_IGN, SIG_SETMASK, SIG_UNBLOCK, SI_KERNEL,
    SI_USER, SOCK_DGRAM, SOCK_RAW, SOCK_STREAM, SPAWN_GROUP_INHERIT, SPAWN_GROUP_NEW, SS_DISABLE,
    SS_ONSTACK, TCGETS, TCSETS, TCSETSF, TCSETSW, TIOCGPGRP, TIOCGPTN, TIOCGWINSZ, TIOCSPGRP,
    TIOCSWINSZ, UI_ABI_VERSION, UI_DISPLAY_NATIVE_PIXEL_FORMAT, UI_EVENT_FLAG_OVERFLOW,
    UI_EVENT_FLAG_PRESSED, UI_EVENT_FLAG_REPEAT, UI_EVENT_KEY, UI_EVENT_POINTER,
    UI_MAX_DAMAGE_RECTS, UI_MAX_EVENTS_PER_READ, UI_MODIFIER_CAPS_LOCK, UI_MODIFIER_LEFT_ALT,
    UI_MODIFIER_LEFT_CTRL, UI_MODIFIER_LEFT_SHIFT, UI_MODIFIER_LEFT_SUPER, UI_MODIFIER_NUM_LOCK,
    UI_MODIFIER_RIGHT_ALT, UI_MODIFIER_RIGHT_CTRL, UI_MODIFIER_RIGHT_SHIFT,
    UI_MODIFIER_RIGHT_SUPER, UI_MODIFIER_SCROLL_LOCK, UI_POINTER_BUTTON_BACK,
    UI_POINTER_BUTTON_FORWARD, UI_POINTER_BUTTON_LEFT, UI_POINTER_BUTTON_MIDDLE,
    UI_POINTER_BUTTON_RIGHT, UI_TIMEOUT_INFINITE, VEOF, VEOL, VERASE, VINTR, VKILL, VMIN, VQUIT,
    VSUSP, VTIME, WCONTINUED, WNOHANG, WUNTRACED,
};
pub use thread::{
    ThreadCreate, ThreadJoinResult, THREAD_ABI_VERSION, THREAD_CREATE_SIZE,
    THREAD_JOIN_RESULT_SIZE, THREAD_MAX_PER_PROCESS, THREAD_STACK_MAX, THREAD_STACK_MIN,
};
pub use wait::{
    WaitItem, WAIT_ABI_VERSION, WAIT_INTEREST_ALL, WAIT_INTEREST_READABLE, WAIT_INTEREST_UI_INPUT,
    WAIT_INTEREST_WRITABLE, WAIT_ITEM_SIZE, WAIT_MAX_ITEMS, WAIT_READY_ALL, WAIT_READY_HANGUP,
    WAIT_READY_READABLE, WAIT_READY_UI_INPUT, WAIT_READY_WRITABLE, WAIT_SOURCE_UI,
    WAIT_TIMEOUT_INFINITE,
};
pub use windows::{WINDOWS_INITRAMFS_ROOT, WINDOWS_NATIVE_ROOT, WINDOWS_SYSTEM_DRIVE};
